FileVersion = 1
Dependencies = {corlib = "*", "OpenToolkit.Mathematics" = "*"}

[Project]
Name = "OpenToolkit.Mathematics.Tests"
StartupObject = "Program"

[Configs.Debug.Win64]
BuildKind = "Test"
